name: "Install toolchains"
description: "Install toolchains"
runs:
  using: "composite"
  steps:
    - run: sudo apt-get install build-essential cmake pkg-config libssl-dev git build-essential llvm clang libclang-dev
      shell: bash

