[profile.release]
panic = "unwind"
opt-level = 3

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[profile.testnet]
inherits = "release"
debug = 1 # debug symbols are useful for profilers
debug-assertions = true
overflow-checks = true

[workspace]
resolver = "2"

exclude = [
	"substrate",
	"subxt",
	"webpki",
	"ring",
	"native-nostd-hasher",
	"standalone/pruntime",
	"crates/pink/examples",
	"crates/pink/sidevm/examples",
]

members = [
	"standalone/executor",
	"standalone/rpc",
	"standalone/node",
	"standalone/runtime",
	"standalone/pherry",
	"standalone/replay",
	"standalone/headers-cache",
	"crates/phala-trie-storage",
	"crates/phala-mq",
	"crates/phala-crypto",
	"crates/phala-node-rpc-ext",
	"crates/phala-types",
	"crates/prpc",
	"crates/prpc-build",
	"crates/phactory",
	"crates/phactory/api",
	"crates/phactory/pal",
	"crates/phala-types",
	"crates/phala-async-executor",
	"crates/phala-allocator",
	"crates/wasmer-tunables",
	"crates/phala-rocket-middleware",
	"crates/pink",
	"crates/pink/pink-extension",
	"crates/pink/pink-extension-runtime",
	"crates/phaxt",
	"crates/pink/pink-extension/macro",
	"crates/pink/sidevm/host-runtime",
	"crates/pink/sidevm/env",
	"crates/pink/sidevm/macro",
	"crates/pink/sidevm/logger",
	"crates/pink/sidevm/sidevm",
	"crates/phala-serde-more",
	"crates/rustfmt-snippet",
	"crates/reqwest-env-proxy",
	"pallets/phala",
	"pallets/phala/mq-runtime-api",
	"scripts/toml-upgrade-version",
	"scripts/debug-cli"
]
