[profile.release]
panic = "unwind"
opt-level = 3

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[profile.testnet]
inherits = "release"
debug = 1 # debug symbols are useful for profilers
debug-assertions = true
overflow-checks = true

[workspace]
resolver = "2"

exclude = [
	"subxt",
	"vendor/webpki",
	"vendor/ring",
	"crates/pink/examples",
	"crates/pink/sidevm/examples",
	"crates/sgx-api-lite",
	"standalone/pruntime",
	"standalone/prouter",
]

members = [
	"standalone/executor",
	"standalone/rpc",
	"standalone/node",
	"standalone/runtime",
	"standalone/pherry",
	"standalone/replay",
	"standalone/headers-cache",
	"standalone/sfq-test",
	"crates/phala-trie-storage",
	"crates/phala-mq",
	"crates/phala-crypto",
	"crates/phala-node-rpc-ext",
	"crates/phala-types",
	"crates/prpc",
	"crates/prpc-build",
	"crates/phactory",
	"crates/phactory/api",
	"crates/phactory/pal",
	"crates/phala-types",
	"crates/phala-async-executor",
	"crates/phala-allocator",
	"crates/wasmer-tunables",
	"crates/phala-rocket-middleware",
	"crates/pink",
	"crates/pink/pink-extension",
	"crates/pink/pink-extension-runtime",
	"crates/phaxt",
	"crates/pink/pink-extension/macro",
	"crates/pink/sidevm/host-runtime",
	"crates/pink/sidevm/env",
	"crates/pink/sidevm/macro",
	"crates/pink/sidevm/logger",
	"crates/pink/sidevm/sidevm",
	"crates/phala-serde-more",
	"crates/rustfmt-snippet",
	"crates/reqwest-env-proxy",
	"crates/phala-fair-queue",
	"pallets/phala",
	"pallets/phala/mq-runtime-api",
	"scripts/debug-cli"
]

[patch.crates-io]
rocket = { version = "0.5.0-rc.2", git = "https://github.com/SergioBenitez/Rocket" }

# Forked 0.18.0 with additional port zstd-sys dependency upgrade
rocksdb = { git = "https://github.com/jasl/rust-rocksdb", branch = "v0.18" }

# For pink-extension-runtime, it will introduce Substrate from crates-io which usually different with polkadot-branch
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
